services:
  # MinIO - The S3 Clone
  zuluflow-minio:
    image: minio/minio
    container_name: zuluflow-minio
    ports:
      - "9000:9000"  # API Port (The Java App talks to this)
      - "9001:9001"  # Console Port (You login here with Chrome)
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data: